In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
plt.style.use('ggplot')
import numpy as np

In [ ]:
# Extract data from amazon.csv
amazon_metadata_df = pd.read_csv('resources/csv/amazon_prime_titles.csv')
amazon_metadata_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [ ]:
amazon_df = amazon_metadata_df[["title", "country","release_year","description"]]
amazon_df.head(10)

,title,country,release_year,description
0,The Grand Seduction,Canada,2014,A small fishing village must procure a local d...
1,Take Care Good Night,India,2018,A Metro Family decides to fight a Cyber Crimin...
2,Secrets of Deception,United States,2017,After a man discovers his wife is cheating on ...
3,Pink: Staying True,United States,2014,"Pink breaks the mold once again, bringing her ..."
4,Monster Maker,United Kingdom,1989,Teenage Matt Banting wants to work with a famo...
5,Living With Dinosaurs,United Kingdom,1989,The story unfolds in a an English seaside town...
6,Hired Gun,United States,2017,"They are the ""First Call, A-list"" musicians, j..."
7,Grease Live!,United States,2016,"This honest, uncompromising comedy chronicles ..."
8,Global Meltdown,Canada,2017,A helicopter pilot and an environmental scient...
9,David's Mother,United States,1994,Sally Goodson is a devoted mother to her autis...

In [ ]:
# Extract data from disney.csv
disney_metadata_df = pd.read_csv('resources/csv/disney_plus_titles.csv')
disney_metadata_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...

In [ ]:
disney_df = disney_metadata_df[["title", "country","release_year","description"]]
disney_df.head(10)

,title,country,release_year,description
0,Duck the Halls: A Mickey Mouse Christmas Special,NaN,2016,Join Mickey and the gang as they duck the halls!
1,Ernest Saves Christmas,NaN,1988,Santa Claus passes his magic bag to a new St. ...
2,Ice Age: A Mammoth Christmas,United States,2011,Sid the Sloth is on Santa's naughty list.
3,The Queen Family Singalong,NaN,2021,"This is real life, not just fantasy!"
4,The Beatles: Get Back,NaN,2021,A three-part documentary from Peter Jackson ca...
5,Becoming Cousteau,United States,2021,An inside look at the legendary life of advent...
6,Hawkeye,NaN,2021,Clint Barton/Hawkeye must team up with skilled...
7,Port Protection Alaska,United States,2015,Residents of Port Protection must combat volat...
8,Secrets of the Zoo: Tampa,United States,2019,A day in the life at ZooTampa is anything but ...
9,A Muppets Christmas: Letters To Santa,United States,2008,Celebrate the holiday season with all your fav...

In [ ]:
# Extract data from hulu.csv
hulu_metadata_df = pd.read_csv('resources/csv/hulu_titles.csv')
hulu_metadata_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...

In [ ]:
hulu_df = hulu_metadata_df[["title", "country","release_year","description"]]
hulu_df.head(10)

,title,country,release_year,description
0,Ricky Velez: Here's Everything,NaN,2021,​Comedian Ricky Velez bares it all with his ho...
1,Silent Night,NaN,2020,"Mark, a low end South London hitman recently r..."
2,The Marksman,NaN,2021,A hardened Arizona rancher tries to protect an...
3,Gaia,NaN,2021,A forest ranger and two survivalists with a cu...
4,Settlers,NaN,2021,Mankind's earliest settlers on the Martian fro...
5,The Halloween Candy Magic Pet,NaN,2021,Join Mila and Morphle on a mystery-filled Hall...
6,The Evil Next Door,NaN,2020,"New to her role as a stepmom, a young woman mo..."
7,The Next Thing You Eat,NaN,2021,With the unique insights and experience of Ugl...
8,Queens,NaN,2021,Four women in their 40s reunite for a chance t...
9,The Bachelorette,United States,2003,ABC's romance reality show lets one lucky lady...

In [ ]:
# Extract data from netflix.csv
netflix_metadata_df = pd.read_csv('resources/csv/netflix_titles.csv')
netflix_metadata_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
netflix_df = netflix_metadata_df[["title", "country","release_year","description"]]
netflix_df.head(10)

,title,country,release_year,description
0,Dick Johnson Is Dead,United States,2020,"As her father nears the end of his life, filmm..."
1,Blood & Water,South Africa,2021,"After crossing paths at a party, a Cape Town t..."
2,Ganglands,NaN,2021,To protect his family from a powerful drug lor...
3,Jailbirds New Orleans,NaN,2021,"Feuds, flirtations and toilet talk go down amo..."
4,Kota Factory,India,2021,In a city of coaching centers known to train I...
5,Midnight Mass,NaN,2021,The arrival of a charismatic young priest brin...
6,My Little Pony: A New Generation,NaN,2021,Equestria's divided. But a bright-eyed hero be...
7,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",1993,"On a photo shoot in Ghana, an American model s..."
8,The Great British Baking Show,United Kingdom,2021,A talented batch of amateur bakers face off in...
9,The Starling,United States,2021,A woman adjusting to life after a loss contend...

In [ ]:
platform = input("Enter movie or tv show to know which streaming platform has it")
print("Username is: " + platform)

Enter movie or tv show to know which streaming platform has itKota Factory
Username is: Kota Factory

In [ ]:
amazon_title = amazon_df.loc[amazon_df['title'].str.contains( platform , case=False)]
amazon_title

Empty DataFrame
Columns: [title, country, release_year, description]
Index: []

In [ ]:
disney_title = disney_df.loc[disney_df['title'].str.contains( platform , case=False)]
disney_title

Empty DataFrame
Columns: [title, country, release_year, description]
Index: []

In [ ]:
hulu_title = hulu_df.loc[hulu_df['title'].str.contains( platform , case=False)]
hulu_title

Empty DataFrame
Columns: [title, country, release_year, description]
Index: []

In [ ]:
netflix_title = netflix_df.loc[netflix_df['title'].str.contains( platform , case=False)]
netflix_title

,title,country,release_year,description
4,Kota Factory,India,2021,In a city of coaching centers known to train I...

In [ ]:
count_amazon= amazon_title["title"].count()
count_disney= disney_title["title"].count()
count_hulu= hulu_title["title"].count()
count_netflix= netflix_title["title"].count()

In [ ]:
if count_amazon > 0:
    print(platform + " is avaliable on Amazon Prime")
else:
    print(platform + " is NOT avaliable on Amazon Prime")

Kota Factory is NOT avaliable on Amazon Prime

In [ ]:
if count_disney > 0:
    print(platform + " is avaliable on Disney Plus")
else:
    print(platform + " is NOT avaliable on Disney Plus")

Kota Factory is NOT avaliable on Disney Plus

In [ ]:
if count_hulu > 0:
    print(platform + " is avaliable on Hulu")
else:
    print(platform + " is NOT avaliable on Hulu")

Kota Factory is NOT avaliable on Hulu

In [ ]:
if count_netflix > 0:
    print(platform + " is avaliable on Netflix")
else:
    print(platform + " is NOT avaliable on Netflix")

Kota Factory is avaliable on Netflix